name: weather_riverpod_async
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  json_annotation:
  flutter_riverpod:
  http:
  equatable:
  google_fonts: 4.0.1
  #flutter_bloc:
  #bloc: ^8.0.3
  flutter_weather_bg_null_safety:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail:
  coverage: ^1.0.3
  custom_lint:
  riverpod_lint:
  #bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
